const data = [
  [
    { key: { ru: 'ё', en: '`' }, code: 'Backquote', class: 'button_text' },
    { key: { ru: '1', en: '1' }, code: 'Digit1', class: 'button_digit' },
    { key: { ru: '2', en: '2' }, code: 'Digit2', class: 'button_digit' },
    { key: { ru: '3', en: '3' }, code: 'Digit3', class: 'button_digit' },
    { key: { ru: '4', en: '4' }, code: 'Digit4', class: 'button_digit' },
    { key: { ru: '5', en: '5' }, code: 'Digit5', class: 'button_digit' },
    { key: { ru: '6', en: '6' }, code: 'Digit6', class: 'button_digit' },
    { key: { ru: '7', en: '7' }, code: 'Digit7', class: 'button_digit' },
    { key: { ru: '8', en: '8' }, code: 'Digit8', class: 'button_digit' },
    { key: { ru: '9', en: '9' }, code: 'Digit9', class: 'button_digit' },
    { key: { ru: '0', en: '0' }, code: 'Digit0', class: 'button_digit' },
    { key: { ru: '-', en: '-' }, code: 'Minus', class: 'button_digit' },
    { key: { ru: '=', en: '=' }, code: 'Equal', class: 'button_digit' },
    { key: 'Backspace', code: 'Backspace', class: 'button_backspace' },
  ],
  [
    { key: 'Tab', code: 'Tab', class: 'button_tab' },
    { key: { ru: 'й', en: 'q' }, code: 'KeyQ', class: 'button_text' },
    { key: { ru: 'ц', en: 'w' }, code: 'KeyW', class: 'button_text' },
    { key: { ru: 'у', en: 'e' }, code: 'KeyE', class: 'button_text' },
    { key: { ru: 'к', en: 'r' }, code: 'KeyR', class: 'button_text' },
    { key: { ru: 'е', en: 't' }, code: 'KeyT', class: 'button_text' },
    { key: { ru: 'н', en: 'y' }, code: 'KeyY', class: 'button_text' },
    { key: { ru: 'г', en: 'u' }, code: 'KeyU', class: 'button_text' },
    { key: { ru: 'ш', en: 'i' }, code: 'KeyI', class: 'button_text' },
    { key: { ru: 'щ', en: 'o' }, code: 'KeyO', class: 'button_text' },
    { key: { ru: 'з', en: 'p' }, code: 'KeyP', class: 'button_text' },
    { key: { ru: 'х', en: '[' }, code: 'BracketLeft', class: 'button_text' },
    { key: { ru: 'ъ', en: ']' }, code: 'BracketRight', class: 'button_text' },
    { key: { ru: '\\', en: '\\' }, code: 'Backslash', class: 'button_text' },
    { key: 'Del', code: 'Delete', class: 'button_del' },
  ],
  [
    { key: 'CapsLock', code: 'CapsLock', class: 'button_capslock' },
    { key: { ru: 'ф', en: 'a' }, code: 'KeyA', class: 'button_text' },
    { key: { ru: 'ы', en: 's' }, code: 'KeyS', class: 'button_text' },
    { key: { ru: 'в', en: 'd' }, code: 'KeyD', class: 'button_text' },
    { key: { ru: 'а', en: 'f' }, code: 'KeyF', class: 'button_text' },
    { key: { ru: 'п', en: 'g' }, code: 'KeyG', class: 'button_text' },
    { key: { ru: 'р', en: 'h' }, code: 'KeyH', class: 'button_text' },
    { key: { ru: 'о', en: 'j' }, code: 'KeyJ', class: 'button_text' },
    { key: { ru: 'л', en: 'k' }, code: 'KeyK', class: 'button_text' },
    { key: { ru: 'д', en: 'l' }, code: 'KeyL', class: 'button_text' },
    { key: { ru: 'ж', en: ';' }, code: 'Semicolon', class: 'button_text' },
    { key: { ru: 'э', en: '\'' }, code: 'Quote', class: 'button_text' },
    { key: 'Enter', code: 'Enter', class: 'button_enter' },
  ],
  [
    { key: 'Shift', code: 'ShiftLeft', class: 'button_leftshift' },
    { key: { ru: 'я', en: 'z' }, code: 'KeyZ', class: 'button_text' },
    { key: { ru: 'ч', en: 'x' }, code: 'KeyX', class: 'button_text' },
    { key: { ru: 'с', en: 'c' }, code: 'KeyC', class: 'button_text' },
    { key: { ru: 'м', en: 'v' }, code: 'KeyV', class: 'button_text' },
    { key: { ru: 'и', en: 'b' }, code: 'KeyB', class: 'button_text' },
    { key: { ru: 'т', en: 'n' }, code: 'KeyN', class: 'button_text' },
    { key: { ru: 'ь', en: 'm' }, code: 'KeyM', class: 'button_text' },
    { key: { ru: 'б', en: ',' }, code: 'Comma', class: 'button_text' },
    { key: { ru: 'ю', en: '.' }, code: 'Period', class: 'button_text' },
    { key: { ru: '.', en: '/' }, code: 'Slash', class: 'button_text' },
    { key: '▲', code: 'ArrowUp' },
    { key: 'Shift', code: 'ShiftRight', class: 'button_rightshift' },
  ],
  [
    { key: 'Ctrl', code: 'ControlLeft', class: 'button_leftctrl' },
    { key: 'Win', code: 'MetaLeft', class: 'button_win' },
    { key: 'Alt', code: 'AltLeft', class: 'button_leftalt' },
    { key: ' ', code: 'Space', class: 'button_space' },
    { key: 'Alt', code: 'AltRight', class: 'button_rightalt' },
    { key: '◄', code: 'ArrowLeft' },
    { key: '▼', code: 'ArrowDown' },
    { key: '►', code: 'ArrowRight' },
    { key: 'Ctrl', code: 'ControlRight', class: 'button_rightctrl' },
  ],
];

export default data;
