const data = [
  [
    { key: { ru: 'ё', en: '`' }, code: 'Backquote' },
    { key: { ru: '1', en: '1' }, code: 'Digit1' },
    { key: { ru: '2', en: '2' }, code: 'Digit2' },
    { key: { ru: '4', en: '4' }, code: 'Digit4' },
    { key: { ru: '5', en: '5' }, code: 'Digit5' },
    { key: { ru: '3', en: '3' }, code: 'Digit3' },
    { key: { ru: '6', en: '6' }, code: 'Digit6' },
    { key: { ru: '7', en: '7' }, code: 'Digit7' },
    { key: { ru: '8', en: '8' }, code: 'Digit8' },
    { key: { ru: '9', en: '9' }, code: 'Digit9' },
    { key: { ru: '0', en: '0' }, code: 'Digit0' },
    { key: { ru: '-', en: '-' }, code: 'Minus' },
    { key: { ru: '=', en: '=' }, code: 'Equal' },
    { key: 'Backspace', code: 'Backspace', class: 'button_backspace' },
  ],
  [
    { key: 'Tab', code: 'Tab', class: 'button_tab' },
    { key: { ru: 'й', en: 'q' }, code: 'KeyQ' },
    { key: { ru: 'ц', en: 'w' }, code: 'KeyW' },
    { key: { ru: 'у', en: 'e' }, code: 'KeyE' },
    { key: { ru: 'к', en: 'r' }, code: 'KeyR' },
    { key: { ru: 'е', en: 't' }, code: 'KeyT' },
    { key: { ru: 'н', en: 'y' }, code: 'KeyY' },
    { key: { ru: 'г', en: 'u' }, code: 'KeyU' },
    { key: { ru: 'ш', en: 'i' }, code: 'KeyI' },
    { key: { ru: 'щ', en: 'o' }, code: 'KeyO' },
    { key: { ru: 'з', en: 'p' }, code: 'KeyP' },
    { key: { ru: 'х', en: '[' }, code: 'BracketLeft' },
    { key: { ru: 'ъ', en: ']' }, code: 'BracketRight' },
    { key: { ru: '\\', en: '\\' }, code: 'Backslash', class: 'key_backslash' },
    { key: 'Del', code: 'Delete', class: 'button_del' },
  ],
  [
    { key: 'CapsLock', code: 'CapsLock', class: 'button_capslock' },
    { key: { ru: 'ф', en: 'a' }, code: 'KeyA' },
    { key: { ru: 'ы', en: 's' }, code: 'KeyS' },
    { key: { ru: 'в', en: 'd' }, code: 'KeyD' },
    { key: { ru: 'а', en: 'f' }, code: 'KeyF' },
    { key: { ru: 'п', en: 'g' }, code: 'KeyG' },
    { key: { ru: 'р', en: 'h' }, code: 'KeyH' },
    { key: { ru: 'о', en: 'j' }, code: 'KeyJ' },
    { key: { ru: 'л', en: 'k' }, code: 'KeyK' },
    { key: { ru: 'д', en: 'l' }, code: 'KeyL' },
    { key: { ru: 'ж', en: ';' }, code: 'Semicolon' },
    { key: { ru: 'э', en: '\'' }, code: 'Quote' },
    { key: 'Enter', code: 'Enter', class: 'button_enter' },
  ],
  [
    { key: 'Shift', code: 'ShiftLeft', class: 'button_leftshift' },
    { key: { ru: 'я', en: 'z' }, code: 'KeyZ' },
    { key: { ru: 'ч', en: 'x' }, code: 'KeyX' },
    { key: { ru: 'с', en: 'c' }, code: 'KeyC' },
    { key: { ru: 'м', en: 'v' }, code: 'KeyV' },
    { key: { ru: 'и', en: 'b' }, code: 'KeyB' },
    { key: { ru: 'т', en: 'n' }, code: 'KeyN' },
    { key: { ru: 'ь', en: 'm' }, code: 'KeyM' },
    { key: { ru: 'б', en: ',' }, code: 'Comma' },
    { key: { ru: 'ю', en: '.' }, code: 'Period' },
    { key: { ru: '.', en: '/' }, code: 'Slash' },
    { key: '▲', code: 'ArrowUp' },
    { key: 'Shift', code: 'ShiftRight', class: 'button_rightshift' },
  ],
  [
    { key: 'Ctrl', code: 'ControlLeft', class: 'button_leftctrl' },
    { key: 'Win', code: 'Windows', class: 'button_win' },
    { key: 'Alt', code: 'AltLeft', class: 'button_leftalt' },
    { key: ' ', code: 'Space', class: 'button_space' },
    { key: 'Alt', code: 'AltRight', class: 'button_rightalt' },
    { key: '◄', code: 'ArrowLeft' },
    { key: '▼', code: 'ArrowDown' },
    { key: '►', code: 'ArrowRight' },
    { key: 'Ctrl', code: 'ControlRight', class: 'button_rightctrl' },
  ],
];

export default data;
